# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suggestions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'suggestions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\nsuggestion\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x0cOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\norder_data\x18\x02 \x01(\t\"1\n\x11SuggestionRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\n\n\x02vc\x18\x02 \x03(\x05\"H\n\x04\x42ook\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04link\x18\x04 \x01(\t\"K\n\x13SuggestionsResponse\x12(\n\x0esuggestedBooks\x18\x01 \x03(\x0b\x32\x10.suggestion.Book\x12\n\n\x02vc\x18\x02 \x03(\x05\x32\xa4\x01\n\x11SuggestionService\x12=\n\tInitOrder\x12\x18.suggestion.OrderRequest\x1a\x16.google.protobuf.Empty\x12P\n\x0eGetSuggestions\x12\x1d.suggestion.SuggestionRequest\x1a\x1f.suggestion.SuggestionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=62
  _globals['_ORDERREQUEST']._serialized_end=114
  _globals['_SUGGESTIONREQUEST']._serialized_start=116
  _globals['_SUGGESTIONREQUEST']._serialized_end=165
  _globals['_BOOK']._serialized_start=167
  _globals['_BOOK']._serialized_end=239
  _globals['_SUGGESTIONSRESPONSE']._serialized_start=241
  _globals['_SUGGESTIONSRESPONSE']._serialized_end=316
  _globals['_SUGGESTIONSERVICE']._serialized_start=319
  _globals['_SUGGESTIONSERVICE']._serialized_end=483
# @@protoc_insertion_point(module_scope)
