# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x05\x66raud\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x0cOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\norder_data\x18\x02 \x01(\t\",\n\x0c\x46raudRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\n\n\x02vc\x18\x02 \x03(\x05\"+\n\rFraudResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\n\n\x02vc\x18\x02 \x03(\x05\x32\xf7\x01\n\x0c\x46raudService\x12\x38\n\tInitOrder\x12\x13.fraud.OrderRequest\x1a\x16.google.protobuf.Empty\x12\x36\n\tCheckUser\x12\x13.fraud.FraudRequest\x1a\x14.fraud.FraudResponse\x12<\n\x0f\x43heckCreditCard\x12\x13.fraud.FraudRequest\x1a\x14.fraud.FraudResponse\x12\x37\n\nCleanOrder\x12\x13.fraud.FraudRequest\x1a\x14.fraud.FraudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=61
  _globals['_ORDERREQUEST']._serialized_end=113
  _globals['_FRAUDREQUEST']._serialized_start=115
  _globals['_FRAUDREQUEST']._serialized_end=159
  _globals['_FRAUDRESPONSE']._serialized_start=161
  _globals['_FRAUDRESPONSE']._serialized_end=204
  _globals['_FRAUDSERVICE']._serialized_start=207
  _globals['_FRAUDSERVICE']._serialized_end=454
# @@protoc_insertion_point(module_scope)
