syntax = "proto3";

import "google/protobuf/empty.proto";

package fraud;

service FraudService {
    rpc InitOrder(OrderRequest) returns (google.protobuf.Empty);
    rpc CheckUser(FraudRequest) returns (FraudResponse);
    rpc CheckCreditCard(FraudRequest) returns (FraudResponse);
    rpc CleanOrder(FraudRequest) returns (FraudResponse);
}

message OrderRequest{
    string order_id = 1;
    string order_data = 2;
}

message FraudRequest {
    string order_id = 1;
    repeated int32 vc = 2;
}

message FraudResponse {
    string result = 1;
    repeated int32 vc = 2;
}
