{
 "title": "Orchestrator Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_mb_MB{resource=\"memory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (checkout_request_latency_milliseconds_bucket{endpoint=\"/checkout\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active checkout request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(active_checkout_requests)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total checkout request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(checkout_requests_total{endpoint=\"/checkout\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}