{
 "title": "Order Executor Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orders_processed_memory_usage_MB{resource=\"memory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed Order Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(orders_processed_failed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Successful Order Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(orders_processed_success_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}