# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_queue.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'order_queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11order_queue.proto\x12\x0border_queue\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x0cOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\norder_data\x18\x02 \x01(\t\"!\n\x0f\x45nqueueResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"n\n\rOrderResponse\x12\x15\n\x08order_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\norder_data\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\tavailable\x18\x03 \x01(\x08\x42\x0b\n\t_order_idB\r\n\x0b_order_data2\xa0\x01\n\x11OrderQueueService\x12G\n\x0c\x45nqueueOrder\x12\x19.order_queue.OrderRequest\x1a\x1c.order_queue.EnqueueResponse\x12\x42\n\x0c\x44\x65queueOrder\x12\x16.google.protobuf.Empty\x1a\x1a.order_queue.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=63
  _globals['_ORDERREQUEST']._serialized_end=115
  _globals['_ENQUEUERESPONSE']._serialized_start=117
  _globals['_ENQUEUERESPONSE']._serialized_end=150
  _globals['_ORDERRESPONSE']._serialized_start=152
  _globals['_ORDERRESPONSE']._serialized_end=262
  _globals['_ORDERQUEUESERVICE']._serialized_start=265
  _globals['_ORDERQUEUESERVICE']._serialized_end=425
# @@protoc_insertion_point(module_scope)
