// transaction.proto

syntax = "proto3";

import "google/protobuf/empty.proto";

package transaction;

service TransactionVerificationService {
    rpc InitOrder(OrderRequest) returns (google.protobuf.Empty);
    rpc VerifyUser(TransactionRequest) returns (TransactionResponse);
    rpc VerifyAddress(TransactionRequest) returns (TransactionResponse);
    rpc VerifyCreditCard(TransactionRequest) returns (TransactionResponse);
    rpc CleanOrder(TransactionRequest) returns (TransactionResponse);
}

message OrderRequest{
    string order_id = 1;
    string order_data = 2;
}

message TransactionRequest {
    string order_id = 1;
    repeated int32 vc = 2;
}

message TransactionResponse {
    string result = 1;
    repeated int32 vc = 2;
}