# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x0btransaction\x1a\x1bgoogle/protobuf/empty.proto\"%\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\"A\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"T\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"\xb9\x02\n\tOrderData\x12\x1f\n\x04user\x18\x01 \x01(\x0b\x32\x11.transaction.User\x12,\n\x0b\x63redit_card\x18\x02 \x01(\x0b\x32\x17.transaction.CreditCard\x12 \n\x05items\x18\x03 \x03(\x0b\x32\x11.transaction.Item\x12-\n\x0f\x62illing_address\x18\x04 \x01(\x0b\x32\x14.transaction.Address\x12.\n\x10shipping_address\x18\x05 \x01(\x0b\x32\x14.transaction.Address\x12\x17\n\x0fshipping_method\x18\x06 \x01(\t\x12\x15\n\rgift_wrapping\x18\x07 \x01(\x08\x12\x14\n\x0cuser_comment\x18\x08 \x01(\t\x12\x16\n\x0eterms_accepted\x18\t \x01(\x08\"L\n\x0cOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12*\n\norder_data\x18\x02 \x01(\x0b\x32\x16.transaction.OrderData\"-\n\x12TransactionRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03\x63vv\x18\x02 \x01(\x05\"6\n\x1fTransactionVerificationResponse\x12\x13\n\x0bis_verified\x18\x01 \x01(\x08\x32\xc4\x01\n\x1eTransactionVerificationService\x12>\n\tInitOrder\x12\x19.transaction.OrderRequest\x1a\x16.google.protobuf.Empty\x12\x62\n\x11VerifyTransaction\x12\x1f.transaction.TransactionRequest\x1a,.transaction.TransactionVerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=76
  _globals['_USER']._serialized_end=113
  _globals['_CREDITCARD']._serialized_start=115
  _globals['_CREDITCARD']._serialized_end=180
  _globals['_ITEM']._serialized_start=182
  _globals['_ITEM']._serialized_end=220
  _globals['_ADDRESS']._serialized_start=222
  _globals['_ADDRESS']._serialized_end=306
  _globals['_ORDERDATA']._serialized_start=309
  _globals['_ORDERDATA']._serialized_end=622
  _globals['_ORDERREQUEST']._serialized_start=624
  _globals['_ORDERREQUEST']._serialized_end=700
  _globals['_TRANSACTIONREQUEST']._serialized_start=702
  _globals['_TRANSACTIONREQUEST']._serialized_end=747
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_start=749
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_end=803
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=806
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=1002
# @@protoc_insertion_point(module_scope)
