# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x0btransaction\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x0cOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\norder_data\x18\x02 \x01(\t\"2\n\x12TransactionRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\n\n\x02vc\x18\x02 \x03(\x05\"B\n\x1fTransactionVerificationResponse\x12\x13\n\x0bis_verified\x18\x01 \x01(\x08\x12\n\n\x02vc\x18\x02 \x03(\x05\x32\x80\x03\n\x1eTransactionVerificationService\x12>\n\tInitOrder\x12\x19.transaction.OrderRequest\x1a\x16.google.protobuf.Empty\x12[\n\nVerifyUser\x12\x1f.transaction.TransactionRequest\x1a,.transaction.TransactionVerificationResponse\x12^\n\rVerifyAddress\x12\x1f.transaction.TransactionRequest\x1a,.transaction.TransactionVerificationResponse\x12\x61\n\x10VerifyCreditCard\x12\x1f.transaction.TransactionRequest\x1a,.transaction.TransactionVerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=76
  _globals['_ORDERREQUEST']._serialized_end=128
  _globals['_TRANSACTIONREQUEST']._serialized_start=130
  _globals['_TRANSACTIONREQUEST']._serialized_end=180
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_start=182
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_end=248
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=251
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=635
# @@protoc_insertion_point(module_scope)
