# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\"(\n\x0ePrepareRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"\'\n\rCommitRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"&\n\x0c\x41\x62ortRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"\x15\n\x04Vote\x12\r\n\x05ready\x18\x01 \x01(\x08\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32q\n\x0ePaymentService\x12!\n\x07Prepare\x12\x0f.PrepareRequest\x1a\x05.Vote\x12\x1e\n\x06\x43ommit\x12\x0e.CommitRequest\x1a\x04.Ack\x12\x1c\n\x05\x41\x62ort\x12\r.AbortRequest\x1a\x04.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREPAREREQUEST']._serialized_start=17
  _globals['_PREPAREREQUEST']._serialized_end=57
  _globals['_COMMITREQUEST']._serialized_start=59
  _globals['_COMMITREQUEST']._serialized_end=98
  _globals['_ABORTREQUEST']._serialized_start=100
  _globals['_ABORTREQUEST']._serialized_end=138
  _globals['_VOTE']._serialized_start=140
  _globals['_VOTE']._serialized_end=161
  _globals['_ACK']._serialized_start=163
  _globals['_ACK']._serialized_end=185
  _globals['_PAYMENTSERVICE']._serialized_start=187
  _globals['_PAYMENTSERVICE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
