# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book_database.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'book_database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62ook_database.proto\x12\rbook_database\"\x1b\n\x0bReadRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\"/\n\x0cWriteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"2\n\x10\x44\x65\x63rementRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"2\n\x10IncrementRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"E\n\nCASRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpected_value\x18\x02 \x01(\x05\x12\x11\n\tnew_value\x18\x03 \x01(\x05\x32\x81\x03\n\rBooksDatabase\x12?\n\x04Read\x12\x1a.book_database.ReadRequest\x1a\x1b.book_database.ReadResponse\x12\x42\n\x05Write\x12\x1b.book_database.WriteRequest\x1a\x1c.book_database.WriteResponse\x12O\n\x0e\x44\x65\x63rementStock\x12\x1f.book_database.DecrementRequest\x1a\x1c.book_database.WriteResponse\x12O\n\x0eIncrementStock\x12\x1f.book_database.IncrementRequest\x1a\x1c.book_database.WriteResponse\x12I\n\x0e\x43ompareAndSwap\x12\x19.book_database.CASRequest\x1a\x1c.book_database.WriteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=38
  _globals['_READREQUEST']._serialized_end=65
  _globals['_READRESPONSE']._serialized_start=67
  _globals['_READRESPONSE']._serialized_end=96
  _globals['_WRITEREQUEST']._serialized_start=98
  _globals['_WRITEREQUEST']._serialized_end=145
  _globals['_WRITERESPONSE']._serialized_start=147
  _globals['_WRITERESPONSE']._serialized_end=179
  _globals['_DECREMENTREQUEST']._serialized_start=181
  _globals['_DECREMENTREQUEST']._serialized_end=231
  _globals['_INCREMENTREQUEST']._serialized_start=233
  _globals['_INCREMENTREQUEST']._serialized_end=283
  _globals['_CASREQUEST']._serialized_start=285
  _globals['_CASREQUEST']._serialized_end=354
  _globals['_BOOKSDATABASE']._serialized_start=357
  _globals['_BOOKSDATABASE']._serialized_end=742
# @@protoc_insertion_point(module_scope)
